const main = async () => {};

main()
  .then(_ => console.log('Success!!'))
  .catch(_ => console.error('Failure!!'));
